.\" Manpage for pokemon_client.
.TH man 8 "14 May 2018" "1.0" "pokemon_client man page"
.SH NAME
pokemon_client \- Aplicaccion de servidor que simula la captura de Pokemons.
.SH SYNOPSIS
.B pokemon_client
[\fIoptions\fR]
.SH DESCRIPTION
Descripcion larga bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2
bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2 bla2.
.SH OPTIONS
.IP "\-\-host=\fIHOST\fR"
La direccion del host.
.IP "\-\-host=\fIPORT\fR"
La direccion del puerto.
.SH BUGS
No hay aun.
.SH AUTHORS
Andres Flores Martinez <andresfm97@ciencias.unam.mx>
.br
Miguel Concha Vazquez <mconcha@ciencias.unam.mx>
.br
Ángel Ivan Gladin Garcia <angelgladin@ciencias.unam.mx>
