.\" Manpage for pokemon_client.
.TH man 8 "14 May 2018" "1.0" "pokemon_client man page"
.SH NAME
pokemon_client \- Aplicaccion de cliente que simula la captura de Pokemons.
.SH SYNOPSIS
.B pokemon_client
[\fIoptions\fR]
.SH DESCRIPTION
Puede tener una direccion para conectarse a un host de esta manera 
--host=192.168.0.1 (esta direccion la puede poner el usuario) o puede 
no llevar argumentos y se referira a 'localhost'.

El cliente solicita al servidor jugar a capturar un pokémon. Le es presentada una sugerencia luego
de haber iniciado sesión exitosamente con su ID y contraseña. En caso de acceder a la captura, se le
presentan algunos intentos; después de cada uno se debe elegir si se quiere intentar de nuevo en caso de 
haber fallado en el intento previo. Finalmente, en caso de tener éxito, la imagen del pokémon capturada será
guarada en el equipo del cliente.
.SH OPTIONS
.IP "\-\-host=\fIHOST\fR"
La direccion del host.
.SH BUGS
No hay aún.
.SH AUTHORS
Andres Flores Martinez <andresfm97@ciencias.unam.mx>
.br
Miguel Concha Vazquez <mconcha@ciencias.unam.mx>
.br
Ángel Ivan Gladin Garcia <angelgladin@ciencias.unam.mx>
