.\" Manpage for pokemon_client.
.TH man 8 "14 May 2018" "1.0" "pokemon_client man page"
.SH NAME
pokemon_server \- Aplicacion de servidor que simula la captura de Pokemons.
.SH SYNOPSIS
.B pokemon_server
.SH DESCRIPTION
El servidor recibe la solicitud de juego por parte de clientes. A cada uno le ofrece una sugerencia de captura
luego de que hayan iniciado sesion exitosamente como debe verificar. Ademas, inicializa un contador de oportunidades
de captura que ira actualizando por cada intento fallido para capturar al pokemon. Luego de preguntar al cliente si
quiere seguir intentando y en caso de exito de captura, debe transferir al cliente la imagen del pokemon capturado.
.SH BUGS
No hay aun.
.SH AUTHORS
Andres Flores Martinez <andresfm97@ciencias.unam.mx>
.br
Miguel Concha Vazquez <mconcha@ciencias.unam.mx>
.br
Angel Ivan Gladin Garcia <angelgladin@ciencias.unam.mx>
