.\" Manpage for pokemon_client.
.TH man 8 "14 May 2018" "1.0" "pokemon_client man page"
.SH NAME
pokemon_server \- Aplicación de servidor que simula la captura de Pokémons.
.SH SYNOPSIS
.B pokemon_server
.SH DESCRIPTION
El servidor recibe la solicitud de juego por parte de clientes. A cada uno le ofrece una sugerencia de captura
luego de que hayan iniciado sesión exitosamente como debe verificar. Además, inicializa un contador de oportunidades
de captura que irá actualizando por cada intento fallido para capturar al pokémon. Luego de preguntar al cliente si
quiere seguir intentando y en caso de éxito de captura, debe transferir al cliente la imagen del pokémon capturado.
.SH BUGS
No hay aun.
.SH AUTHORS
Andres Flores Martínez <andresfm97@ciencias.unam.mx>
.br
Miguel Concha Vázquez <mconcha@ciencias.unam.mx>
.br
Ángel Iván Gladín García <angelgladin@ciencias.unam.mx>
